package com.amin.radion.constant;

import com.amin.radion.R;

public enum Country {
   AFGHANISTAN                      ("AF", "افغانستان") { @Override  public int getFlag() { return R.drawable.afghanistan;  } },
   ALBANIA                          ("AL", "آلبانی"){ @Override  public int getFlag() { return R.drawable.albania;  } },
   ALGERIA                          ("DZ", "الجزایر"){ @Override  public int getFlag() { return R.drawable.algeria;  } },
   AMERICAN_SAMOA                   ("AS", "ساموا"){ @Override  public int getFlag() { return R.drawable.americansamoa;  } },
   ANDORRA                          ("AD", "آندورا"){ @Override  public int getFlag() { return R.drawable.andorra;  } },
   ANGOLA                           ("AO", "آنگولا"){ @Override  public int getFlag() { return R.drawable.angola;  } },
   ANGUILLA                         ("AI", "آنگولیلا"){ @Override  public int getFlag() { return R.drawable.anguilla;  } },
   ANTARCTICA                       ("AQ", "قطب جنوب"){ @Override  public int getFlag() { return R.drawable.antarctica;  } },
   ANTIGUA_AND_BARBUDA              ("AG", "آنتیگوا و باربودا"){ @Override  public int getFlag() { return R.drawable.antiguaandbarbuda;  } },
   ARGENTINA                        ("AR", "آرژنتین"){ @Override  public int getFlag() { return R.drawable.argentina;  } },
   ARMENIA                          ("AM", "ارمنستان"){ @Override  public int getFlag() { return R.drawable.armenia;  } },
   ARUBA                            ("AW", "آروبا"){ @Override  public int getFlag() { return R.drawable.aruba;  } },
   AUSTRALIA                        ("AU", "استرالیا"){ @Override  public int getFlag() { return R.drawable.australia;  } },
   AUSTRIA                          ("AT", "اتریش"){ @Override  public int getFlag() { return R.drawable.austria;  } },
   AZERBAIJAN                       ("AZ", "آذربایجان"){ @Override  public int getFlag() { return R.drawable.azerbaijan;  } },
   BAHAMAS                          ("BS", "باهاماس"){ @Override  public int getFlag() { return R.drawable.bahamas;  } },
   BAHRAIN                          ("BH", "بحرین"){ @Override  public int getFlag() { return R.drawable.bahrain;  } },
   BANGLADESH                       ("BD", "بنگلداش"){ @Override  public int getFlag() { return R.drawable.bangladesh;  } },
   BARBADOS                         ("BB", "باربادوس"){ @Override  public int getFlag() { return R.drawable.barbados;  } },
   BELARUS                          ("BY", "بلاروس"){ @Override  public int getFlag() { return R.drawable.belarus;  } },
   BELGIUM                          ("BE", "بلژیک"){ @Override  public int getFlag() { return R.drawable.belgium;  } },
   BELIZE                           ("BZ", "بلیز"){ @Override  public int getFlag() { return R.drawable.belize;  } },
   BENIN                            ("BJ", "بنین"){ @Override  public int getFlag() { return R.drawable.benin;  } },
   BERMUDA                          ("BM", "برمودا"){ @Override  public int getFlag() { return R.drawable.bermuda;  } },
   BHUTAN                           ("BT", "بوتان"){ @Override  public int getFlag() { return R.drawable.bhutan;  } },
   BOLIVIA                          ("BO", "بولیوی"){ @Override  public int getFlag() { return R.drawable.bolivia;  } },
   BONAIRE                          ("BQ", "بونیر"){ @Override  public int getFlag() { return R.drawable.bonaire;  } },
   BOSNIA_AND_HERZEGOVINA           ("BA", "بوسنی و هرزگوین"){ @Override  public int getFlag() { return R.drawable.bosniaandherzegovina;  } },
   BOTSWANA                         ("BW", "بوتسوانا"){ @Override  public int getFlag() { return R.drawable.botswana;  } },
   BOUVET_ISLAND                    ("BV", "جزیره بوویت"){ @Override  public int getFlag() { return R.drawable.bouvet;  } },
   BRAZIL                           ("BR", "برزیل"){ @Override  public int getFlag() { return R.drawable.brazil;  } },
   BRITISH_INDIAN_OCEAN_TERRITORY   ("IO", "قلمرو بریتانیا در اقیانوس هند"){ @Override  public int getFlag() { return R.drawable.britishindianoceanterritory;  } },
   BRUNEI_DARUSSALAM                ("BN", "برونئی"){ @Override  public int getFlag() { return R.drawable.brunei;  } },
   BULGARIA                         ("BG", "بلغارستان"){ @Override  public int getFlag() { return R.drawable.bulgaria;  } },
   BURKINA_FASO                     ("BF", "بورکینافاسو"){ @Override  public int getFlag() { return R.drawable.burkinafaso;  } },
   BURUNDI                          ("BI", "بروندی"){ @Override  public int getFlag() { return R.drawable.burundi;  } },
   CAMBODIA                         ("KH", "کامبوج"){ @Override  public int getFlag() { return R.drawable.cambodja;  } },
   CAMEROON                         ("CM", "کامرون"){ @Override  public int getFlag() { return R.drawable.cameroon;  } },
   CANADA                           ("CA", "کانادا"){ @Override  public int getFlag() { return R.drawable.canada;  } },
   CAPE_VERDE                       ("CV", "کیپ ورد"){ @Override  public int getFlag() { return R.drawable.capeverde;  } },
   CAYMAN_ISLANDS                   ("KY", "جزایر کیمن"){ @Override  public int getFlag() { return R.drawable.caymanislands;  } },
   CENTRAL_AFRICAN_REPUBLIC         ("CF", "جمهوری آفریقای مرکزی"){ @Override  public int getFlag() { return R.drawable.centralafricanrepublic;  } },
   CHAD                             ("TD", "چاد"){ @Override  public int getFlag() { return R.drawable.chad;  } },
   CHILE                            ("CL", "شیلی"){ @Override  public int getFlag() { return R.drawable.chile;  } },
   PEOPLES_REPUBLIC_OF_CHINA        ("CN", "جمهوری خلق چین"){ @Override  public int getFlag() { return R.drawable.china;  } },
  CHRISTMAS_ISLAND                  ("CX", "جزیره کریسمس"){ @Override  public int getFlag() { return R.drawable.christmas;  } },
   COCOS_ISLANDS                    ("CC", "جزایر کوکو"){ @Override  public int getFlag() { return R.drawable.cocos_keeling;  } },
   COLOMBIA                         ("CO", "کلمبیا"){ @Override  public int getFlag() { return R.drawable.colombia;  } },
   COMOROS                          ("KM", "کومور"){ @Override  public int getFlag() { return R.drawable.comoros;  } },
   CONGO                            ("CG", "کنگو"){ @Override  public int getFlag() { return R.drawable.congobrazzaville;  } },
   CONGO_THE_DEMOCRATIC_REPUBLIC_OF ("CD", "جمهوری دموکراتیک کنگو"){ @Override  public int getFlag() { return R.drawable.congokinshasa_zaire;  } },
   COOK_ISLANDS                     ("CK", "جزایر کوک"){ @Override  public int getFlag() { return R.drawable.cookislands;  } },
   COSTARICA                        ("CR", "کاستاریکا"){ @Override  public int getFlag() { return R.drawable.costarica;  } },
   COTED_IVOIRE                     ("CI", "ساحل عاج"){ @Override  public int getFlag() { return R.drawable.cotedivoire;  } },
   CROATIA                          ("HR", "کرواسی"){ @Override  public int getFlag() { return R.drawable.croatia;  } },
   CUBA                             ("CU", "کوبا"){ @Override  public int getFlag() { return R.drawable.cuba;  } },
   CURA                             ("CW", "کورا"){ @Override  public int getFlag() { return R.drawable.curacao;  } },
   CYPRUS                           ("CY", "قبرس"){ @Override  public int getFlag() { return R.drawable.cyprus;  } },
   CZECH_REPUBLIC                   ("CZ", "جمهوری چک"){ @Override  public int getFlag() { return R.drawable.czechrepublic;  } },
   DENMARK                          ("DK", "دانمارک"){ @Override  public int getFlag() { return R.drawable.denmark;  } },
   DJIBOUTI                         ("DJ", "جیبوتی"){ @Override  public int getFlag() { return R.drawable.djibouti;  } },
   DOMINICA                         ("DM", "دومنیکا"){ @Override  public int getFlag() { return R.drawable.dominica;  } },
   DOMINICAN_REPUBLIC               ("DO", "جمهوری دومینیکن"){ @Override  public int getFlag() { return R.drawable.dominicanrepublic;  } },
   ECUADOR                          ("EC", "اکوادور"){ @Override  public int getFlag() { return R.drawable.ecuador;  } },
   EGYPT                            ("EG", "مصر"){ @Override  public int getFlag() { return R.drawable.egypt;  } },
   WESTERN_SAHARA                   ("EH", "صحرای غربی"){ @Override  public int getFlag() { return R.drawable.westernsahara;  } },
   EL_SALVADOR                      ("SV", "السالوادور"){ @Override  public int getFlag() { return R.drawable.elsalvador;  } },
   EQUATORIAL_GUINEA                ("GQ", "گینه استوایی"){ @Override  public int getFlag() { return R.drawable.equatorialguinea;  } },
   ERITREA                          ("ER", "اریتره"){ @Override  public int getFlag() { return R.drawable.eritrea;  } },
   ESTONIA                          ("EE", "استونی"){ @Override  public int getFlag() { return R.drawable.estonia;  } },
   ETHIOPIA                         ("ET", "اتیوپی"){ @Override  public int getFlag() { return R.drawable.ethiopia;  } },
   FALKLAND_ISLANDS                 ("FK", "جزایر فالکلند"){ @Override  public int getFlag() { return R.drawable.falkland_malvinas;  } },
   FAROE_ISLANDS                    ("FO", "جزایر فارو"){ @Override  public int getFlag() { return R.drawable.faroes;  } },
   FIJI                             ("FJ", "فیجی"){ @Override  public int getFlag() { return R.drawable.fiji;  } },
   FINLAND                          ("FI", "فنلاند"){ @Override  public int getFlag() { return R.drawable.finland;  } },
   FRANCE                           ("FR", "فرانسه"){ @Override  public int getFlag() { return R.drawable.france;  } },
   FRENCH_GUIANA                    ("GF", "گویان فرانسه"){ @Override  public int getFlag() { return R.drawable.frenchguiana;  } },
   FRENCH_POLYNESIA                 ("PF", "پلینزی فرانسه"){ @Override  public int getFlag() { return R.drawable.french_polynesi;  } },
   FRENCH_SOUTHERN_TERRITORIES      ("TF", "مناطق جنوبی فرانسه"){ @Override  public int getFlag() { return R.drawable.frenchsouthernandantarcticlands;  } },
   GABON                            ("GA", "گابون"){ @Override  public int getFlag() { return R.drawable.gabon;  } },
   GAMBIA                           ("GM", "گامبیا"){ @Override  public int getFlag() { return R.drawable.gambia;  } },
   GEORGIA                          ("GE", "گرجستان"){ @Override  public int getFlag() { return R.drawable.georgia;  } },
   GERMANY                          ("DE", "آلمان"){ @Override  public int getFlag() { return R.drawable.germany;  } },
   GHANA                            ("GH", "غنا"){ @Override  public int getFlag() { return R.drawable.ghana;  } },
   GIBRALTAR                        ("GI", "جبل الطارق"){ @Override  public int getFlag() { return R.drawable.gibraltar;  } },
   GREECE                           ("GR", "یونان"){ @Override  public int getFlag() { return R.drawable.greece;  } },
   GREENLAND                        ("GL", "گرینلند"){ @Override  public int getFlag() { return R.drawable.greenland;  } },
   GRENADA                          ("GD", "گرانادا"){ @Override  public int getFlag() { return R.drawable.grenada;  } },
   GUADELOUPE                       ("GP", "جزیره گوادلوپ"){ @Override  public int getFlag() { return R.drawable.guadeloupe;  } },
   GUAM                             ("GU", "گوام"){ @Override  public int getFlag() { return R.drawable.guam;  } },
   GUATEMALA                        ("GT", "گواتمالا"){ @Override  public int getFlag() { return R.drawable.guatemala;  } },
   GUINEA                           ("GN", "گوینا"){ @Override  public int getFlag() { return R.drawable.guinea;  } },
   GUINEA_BISSAU                    ("GW", "گینه بیسائو"){ @Override  public int getFlag() { return R.drawable.guineabissau;  } },
   GUYANA                           ("GY", "گویانا"){ @Override  public int getFlag() { return R.drawable.guyana;  } },
   HAITI                            ("HT", "هائیتی"){ @Override  public int getFlag() { return R.drawable.haiti;  } },
   HEARD_ISLAND_AND_MCDONALD_ISLANDS("HM", "جزیره هرد و جزایر مک دونالد"){ @Override  public int getFlag() { return R.drawable.heard_island_and_mcdonald;  } },
   HONDURAS                         ("HN", "هندوراس"){ @Override  public int getFlag() { return R.drawable.honduras;  } },
   HONG_KONG                        ("HK", "هنگ کنگ"){ @Override  public int getFlag() { return R.drawable.hongkong;  } },
   HUNGARY                          ("HU", "مجارستان"){ @Override  public int getFlag() { return R.drawable.hungary;  } },
   ICELAND                          ("IS", "ایسلند"){ @Override  public int getFlag() { return R.drawable.iceland;  } },
   INDIA                            ("IN", "هند"){ @Override  public int getFlag() { return R.drawable.india;  } },
   INDONESIA                        ("ID", "اندونزی"){ @Override  public int getFlag() { return R.drawable.indonezia;  } },
   IRAN_ISLAMIC_REPUBLIC_OF         ("IR", " جمهوری اسلامی ایران"){ @Override  public int getFlag() { return R.drawable.iran;  } },
   IRAQ                             ("IQ", "عراق"){ @Override  public int getFlag() { return R.drawable.iraq;  } },
   IRELAND                          ("IE", "ایرلند"){ @Override  public int getFlag() { return R.drawable.ireland;  } },
   ISRAEL                           ("IL", "اسرائيل"){ @Override  public int getFlag() { return R.drawable.israel;  } },
   ISE_LOF_MAN                      ("IM", "جزیره من"){ @Override  public int getFlag() { return R.drawable.isleofman;  } },
   ITALY                            ("IT", "ایتالیا"){ @Override  public int getFlag() { return R.drawable.italy;  } },
   JAMAICA                          ("JM", "جامائیکا"){ @Override  public int getFlag() { return R.drawable.jamaica;  } },
   JAPAN                            ("JP", "ژاپن"){ @Override  public int getFlag() { return R.drawable.japan;  } },
   JORDAN                           ("JO", "اردن"){ @Override  public int getFlag() { return R.drawable.jordan;  } },
   KAZAKHSTAN                       ("KZ", "قزاقستان"){ @Override  public int getFlag() { return R.drawable.kazakhstan;  } },
   KENYA                            ("KE", "کنیا"){ @Override  public int getFlag() { return R.drawable.kenya;  } },
   KIRIBATI                         ("KI", "کیریباتی"){ @Override  public int getFlag() { return R.drawable.kiribati;  } },
   KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF        ("KP", "کره شمالی"){ @Override  public int getFlag() { return R.drawable.northkorea;  } },
   KOREA_REPUBLIC_OF                           ("KR", "کره جنوبی"){ @Override  public int getFlag() { return R.drawable.southkorea;  } },
   KOSOVO                                      ("XK", "کوزوو"){ @Override  public int getFlag() { return R.drawable.kosovo;  } },
   KUWAIT                                      ("KW", "کویت"){ @Override  public int getFlag() { return R.drawable.kuwait;  } },
   KYRGYZSTAN                                  ("KG", "قرقیزستان"){ @Override  public int getFlag() { return R.drawable.kyrgyzstan;  } },
   LAO_PEOPLES_DEMOCRATIC_REPUBLIC             ("LA", "جمهوری دموکراتیک لائوس"){ @Override  public int getFlag() { return R.drawable.laos;  } },
   LATVIA                                      ("LV", "لتونی"){ @Override  public int getFlag() { return R.drawable.latvia;  } },
   LEBANON                                     ("LB", "لبنان"){ @Override  public int getFlag() { return R.drawable.lebanon;  } },
   LESOTHO                                     ("LS", "لسوتو"){ @Override  public int getFlag() { return R.drawable.lesotho;  } },
   LIBERIA                                     ("LR", "ليبريا"){ @Override  public int getFlag() { return R.drawable.liberia;  } },
   LIBYAN_ARAB_JAMAHIRIYA                      ("LY", "لیبی"){ @Override  public int getFlag() { return R.drawable.libya;  } },
   LIECHTENSTEIN                               ("LI", "لیختن اشتاین"){ @Override  public int getFlag() { return R.drawable.liechtenshein;  } },
   LITHUANIA                                   ("LT", "لیتوانی"){ @Override  public int getFlag() { return R.drawable.lithuania;  } },
   LUXEMBOURG                                  ("LU", "لوکزامبورگ"){ @Override  public int getFlag() { return R.drawable.luxembourg;  } },
   MACAO                                       ("MO", "ماکائو"){ @Override  public int getFlag() { return R.drawable.macao;  } },
   MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF   ("MK", "مقدونیه جمهوری سابق یوگسلاوی"){ @Override  public int getFlag() { return R.drawable.macedonia;  } },
   MADAGASCAR                                  ("MG", "ماداگاسکار"){ @Override  public int getFlag() { return R.drawable.madagascar;  } },
   MALAWI                                      ("MW", "مالاوی"){ @Override  public int getFlag() { return R.drawable.malawi;  } },
   MALAYSIA                                    ("MY", "مالزی"){ @Override  public int getFlag() { return R.drawable.malaysia;  } },
   MALDIVES                                    ("MV", "مالدیو"){ @Override  public int getFlag() { return R.drawable.maldives;  } },
   MALI                                        ("ML", "مالی"){ @Override  public int getFlag() { return R.drawable.mali;  } },
   MALTA                                       ("MT", "مالتا"){ @Override  public int getFlag() { return R.drawable.malta;  } },
   MARSHALL_ISLANDS                            ("MH", "جزایر مارشال"){ @Override  public int getFlag() { return R.drawable.marshallislands;  } },
   MARTINIQUE                                  ("MQ", "مارتینک"){ @Override  public int getFlag() { return R.drawable.martinique;  } },
   MAURITANIA                                  ("MR", "موریتانیا"){ @Override  public int getFlag() { return R.drawable.mauritania;  } },
   MAURITIUS                                   ("MU", "موریس"){ @Override  public int getFlag() { return R.drawable.mauritius;  } },
   MAYOTTE                                     ("YT", "مایوتت"){ @Override  public int getFlag() { return R.drawable.mayotte;  } },
   MEXICO                                      ("MX", "مکزیک"){ @Override  public int getFlag() { return R.drawable.mexico;  } },
   MICRONESIA_FEDERATED_STATES_OF              ("FM", "میکرونزیا ، ایالات فدرال از"){ @Override  public int getFlag() { return R.drawable.micronesia;  } },
   MOLDOVA_REPUBLIC_OF                         ("MD", "مولداوی"){ @Override  public int getFlag() { return R.drawable.moldova;  } },
   MONACO                                      ("MC", "موناکو"){ @Override  public int getFlag() { return R.drawable.monaco;  } },
   MONGOLIA                                    ("MN", "مغولستان"){ @Override  public int getFlag() { return R.drawable.mongolia;  } },
   MONTSERRAT                                  ("MS", "مونتسرات"){ @Override  public int getFlag() { return R.drawable.montserrat;  } },
   MON‌TENEGRO                                 ("ME", "مونته نگرو"){ @Override  public int getFlag() { return R.drawable.montenegro;  } },
   MOROCCO                                     ("MA", "مراکش"){ @Override  public int getFlag() { return R.drawable.morocco;  } },
   MOZAMBIQUE                                  ("MZ", "موزامبیک"){ @Override  public int getFlag() { return R.drawable.mozambique;  } },
   MYANMAR                                     ("MM", "میانمار"){ @Override  public int getFlag() { return R.drawable.myanmar_burma;  } },
   NAMIBIA                                     ("NA", "نامیبیا"){ @Override  public int getFlag() { return R.drawable.namibia;  } },
   NAURU                                       ("NR", "ناورو"){ @Override  public int getFlag() { return R.drawable.nauru;  } },
   NEPAL                                       ("NP", "نپال"){ @Override  public int getFlag() { return R.drawable.nepal;  } },
   NETHERLANDS                                 ("NL", "هلند"){ @Override  public int getFlag() { return R.drawable.netherlands;  } },
   NETHERLANDS_ANTILLES                        ("AN", "آنتیل هلند"){ @Override  public int getFlag() { return R.drawable.netherlandsantilles;  } },
   NEW_CALEDONIA                               ("NC", "کالدونیای جدید"){ @Override  public int getFlag() { return R.drawable.newcaledonia;  } },
   NEW_ZEALAND                                 ("NZ", "نیوزلند"){ @Override  public int getFlag() { return R.drawable.newzealand;  } },
   NICARAGUA                                   ("NI", "نیکاراگوئه"){ @Override  public int getFlag() { return R.drawable.nicaragua;  } },
   NIGER                                       ("NE", "نیجر"){ @Override  public int getFlag() { return R.drawable.niger;  } },
   NIGERIA                                     ("NG", "نیجریه"){ @Override  public int getFlag() { return R.drawable.nigeria;  } },
   NIUE                                        ("NU", "نیو"){ @Override  public int getFlag() { return R.drawable.niue;  } },
   NORFOLK_ISLAND                              ("NF", "جزیره نورفولک"){ @Override  public int getFlag() { return R.drawable.norfolk;  } },
   NORTHERN_MARIANA_ISLANDS                    ("MP", "جزایر ماریانای شمالی"){ @Override  public int getFlag() { return R.drawable.northernmariana;  } },
   NORWAY                                      ("NO", "نروژ"){ @Override  public int getFlag() { return R.drawable.norway;  } },
   OMAN                                        ("OM", "عمان"){ @Override  public int getFlag() { return R.drawable.oman;  } },
   PAKISTAN                                    ("PK", "پاکستان"){ @Override  public int getFlag() { return R.drawable.pakistan;  } },
   PALAU                                       ("PW", "پالائو"){ @Override  public int getFlag() { return R.drawable.palau;  } },
   PALESTINIAN_TERRITORY_OCCUPIED              ("PS", "فلستین"){ @Override  public int getFlag() { return R.drawable.palestine;  } },
   PANAMA                                      ("PA", "پاناما"){ @Override  public int getFlag() { return R.drawable.panama;  } },
   PAPUA_NEW_GUINEA                            ("PG", "پاپوآ گینه نو"){ @Override  public int getFlag() { return R.drawable.papuanewguinea;  } },
   PARAGUAY                                    ("PY", "پاراگوئه"){ @Override  public int getFlag() { return R.drawable.paraguay;  } },
   PERU                                        ("PE", "پرو"){ @Override  public int getFlag() { return R.drawable.peru;  } },
   PHILIPPINES                                 ("PH", "فیلیپین"){ @Override  public int getFlag() { return R.drawable.philippines;  } },
   PITCAIRN                                    ("PN", " پیکریرن"){ @Override  public int getFlag() { return R.drawable.pitcairn;  } },
   POLAND                                      ("PL", "لهستان"){ @Override  public int getFlag() { return R.drawable.poland;  } },
   PORTUGAL                                    ("PT", "پرتغال"){ @Override  public int getFlag() { return R.drawable.portugal;  } },
   PUERTO_RICO                                 ("PR", "پورتوریکو"){ @Override  public int getFlag() { return R.drawable.puertorico;  } },
   QATAR                                       ("QA", "قطر"){ @Override  public int getFlag() { return R.drawable.qatar;  } },
   REUNION                                     ("RE", "ریونیون"){ @Override  public int getFlag() { return R.drawable.reunion;  } },
   ROMANIA                                     ("RO", "رومانی"){ @Override  public int getFlag() { return R.drawable.romania;  } },
   RUSSIAN_FEDERATION                          ("RU", "روسیه"){ @Override  public int getFlag() { return R.drawable.russianfederation;  } },
   RWANDA                                      ("RW", "روندا"){ @Override  public int getFlag() { return R.drawable.rwanda;  } },
   SAINT_HELENA                                ("SH", "سنت هلنا"){ @Override  public int getFlag() { return R.drawable.sainthelena;  } },
   SAINT_KITTS_AND_NEVIS                       ("KN", "کیت های مقدس و هرگز"){ @Override  public int getFlag() { return R.drawable.stkittsandnevis;  } },
   SAINT_LUCIA                                 ("LC", "سنت لوسیا"){ @Override  public int getFlag() { return R.drawable.saintlucia;  } },
   SAINT_PIERRE_AND_MIQUELON                   ("PM", "سنت پیر و میکلون"){ @Override  public int getFlag() { return R.drawable.saintpierreandmiquelon;  } },
   SAINT_VINCENT_AND_THE_GRENADINES            ("VC", "سنت وینسنت و گرنادین"){ @Override  public int getFlag() { return R.drawable.stvincentandthegrenadines;  } },
   SAMOA                                       ("WS", "ساموآ"){ @Override  public int getFlag() { return R.drawable.samoa;  } },
   SAN_MARINO                                  ("SM", "سان مارینو"){ @Override  public int getFlag() { return R.drawable.sanmarino;  } },
   SAO_TOME_AND_PRINCIPE                       ("ST", "سائو تومه و پرنسیپ"){ @Override  public int getFlag() { return R.drawable.saotomeandprincipe;  } },
   SAUDI_ARABIA                                ("SA", "عربستان سعودی"){ @Override  public int getFlag() { return R.drawable.saudiarabia;  } },
   SENEGAL                                     ("SN", "سنگال"){ @Override  public int getFlag() { return R.drawable.senegal;  } },
   SERBIA_AND_MONTENEGRO                       ("CS", "صربستان و مونته نگرو"){ @Override  public int getFlag() { return R.drawable.serbia_and_montenegro;  } },
   SERBIA                                      ("RS", "صربستان"){ @Override  public int getFlag() { return R.drawable.serbia_yugoslavia;  } },
   SEYCHELLES                                  ("SC", "سیشل"){ @Override  public int getFlag() { return R.drawable.seychelles;  } },
   SIERRA_LEONE                                ("SL", "سیرا لئون"){ @Override  public int getFlag() { return R.drawable.sierraleone;  } },
   SINGAPORE                                   ("SG", "سنگاپور"){ @Override  public int getFlag() { return R.drawable.singapore;  } },
   SLOVAKIA                                    ("SK", "اسلوواکی"){ @Override  public int getFlag() { return R.drawable.slovakia;  } },
   SLOVENIA                                    ("SI", "اسلوونی"){ @Override  public int getFlag() { return R.drawable.slovenia;  } },
   SOLOMON_ISLANDS                             ("SB", "جزایر سلیمان"){ @Override  public int getFlag() { return R.drawable.solomonislands;  } },
   SOMALIA                                     ("SO", "سومالی"){ @Override  public int getFlag() { return R.drawable.somalia;  } },
   SOUTH_AFRICA                                ("ZA", "آفریقای جنوبی"){ @Override  public int getFlag() { return R.drawable.southafrica;  } },
   SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS    ("GS", "جورجیای جنوبی و جزایر ساندویچ جنوبی"){ @Override  public int getFlag() { return R.drawable.southgeorgiaandsouthsandwich;  } },
   SPAIN                                       ("ES", "اسپانیا"){ @Override  public int getFlag() { return R.drawable.spain;  } },
   SRI_LANKA                                   ("LK", "سری لانکا"){ @Override  public int getFlag() { return R.drawable.srilanka;  } },
   SUDAN                                       ("SD", "سودان"){ @Override  public int getFlag() { return R.drawable.sudan;  } },
   SOUTH_SUDAN                                 ("SS", "سودان جنوبی"){ @Override  public int getFlag() { return R.drawable.south_sudan;  } },
   SURINAME                                    ("SR", "سورینام"){ @Override  public int getFlag() { return R.drawable.suriname;  } },
   SVALBARD_AND_JAN_MAYEN                      ("SJ", "سوالبارد و یان ماین"){ @Override  public int getFlag() { return R.drawable.svalbard_and_jan_mayen;  } },
   SWAZILAND                                   ("SZ", "سوازیلند"){ @Override  public int getFlag() { return R.drawable.swaziland;  } },
   SWEDEN                                      ("SE", "سوئد"){ @Override  public int getFlag() { return R.drawable.sweden;  } },
   SWITZERLAND                                 ("CH", "سوئیس"){ @Override  public int getFlag() { return R.drawable.switzerland;  } },
   SYRIAN_ARAB_REPUBLIC                        ("SY", "سوریه"){ @Override  public int getFlag() { return R.drawable.syria;  } },
   TAIWAN_REPUBLIC_OF_CHINA                    ("TW", "تایوان"){ @Override  public int getFlag() { return R.drawable.taiwan;  } },
   TAJIKISTAN                                  ("TJ", "تاجیکستان"){ @Override  public int getFlag() { return R.drawable.tajikistan;  } },
   TANZANIA_UNITED_REPUBLIC_OF                 ("TZ", "تانزانیا"){ @Override  public int getFlag() { return R.drawable.tanzania;  } },
   THAILAND                                    ("TH", "تایلند"){ @Override  public int getFlag() { return R.drawable.thailand;  } },
   TIMOR_LESTE                                 ("TL", "تیمور شرقی"){ @Override  public int getFlag() { return R.drawable.timorleste;  } },
   TOGO                                        ("TG", "توگو"){ @Override  public int getFlag() { return R.drawable.togo;  } },
   TOKELAU                                     ("TK", "توکلائو"){ @Override  public int getFlag() { return R.drawable.tokelau;  } },
   TONGA                                       ("TO", "تونگا"){ @Override  public int getFlag() { return R.drawable.tonga;  } },
   TRINIDAD_AND_TOBAGO                         ("TT", "ترینیداد و توباگو"){ @Override  public int getFlag() { return R.drawable.trinidadandtobago;  } },
   TUNISIA                                     ("TN", "تونس"){ @Override  public int getFlag() { return R.drawable.tunisia;  } },
   TURKEY                                      ("TR", "ترکیه"){ @Override  public int getFlag() { return R.drawable.turkey;  } },
   TURKMENISTAN                                ("TM", "ترکمنستان"){ @Override  public int getFlag() { return R.drawable.turkmenistan;  } },
   TURKS_AND_CAICOS_ISLANDS                    ("TC", "جزایر تورها و کالیکوس"){ @Override  public int getFlag() { return R.drawable.turksandcaicosislands;  } },
   TUVALU                                      ("TV", "تووالو"){ @Override  public int getFlag() { return R.drawable.tuvalu;  } },
   UGANDA                                      ("UG", "اوگاندا"){ @Override  public int getFlag() { return R.drawable.uganda;  } },
   UKRAINE                                     ("UA", "اکراین"){ @Override  public int getFlag() { return R.drawable.ukraine;  } },
   UNITED_ARAB_EMIRATES                        ("AE", "امارات متحده عربی"){ @Override  public int getFlag() { return R.drawable.unitedarabemirates;  } },
   UNITED_KINGDOM                              ("GB", "انگلستان"){ @Override  public int getFlag() { return R.drawable.unitedkingdom;  } },
   UNITED_STATES                               ("US", "ایالات متحده"){ @Override  public int getFlag() { return R.drawable.unitedstatesofamerica;  } },
   UNITED_STATES_MINOR_OUTLYING_ISLANDS        ("UM", "جزایر کوچک حاشیه های ایالات متحده"){ @Override  public int getFlag() { return R.drawable.unitedstatesminoroutlying;  } },
   URUGUAY                                     ("UY", "اروگوئه"){ @Override  public int getFlag() { return R.drawable.uruguay;  } },
   UZBEKISTAN                                  ("UZ", "ازبکستان"){ @Override  public int getFlag() { return R.drawable.uzbekistan;  } },
   VATICAN_CITY_STATE                          ("VA", "واتیکان"){ @Override  public int getFlag() { return R.drawable.vaticancity;  } },
   VENEZUELA                                   ("VE", "ونزوئلا"){ @Override  public int getFlag() { return R.drawable.venezuela;  } },
   VANUATU                                     ("VU", "واناتو"){ @Override  public int getFlag() { return R.drawable.vanutau;  } },
   VIETNAM                                     ("VN", "ویتنام"){ @Override  public int getFlag() { return R.drawable.vietnam;  } },
   BRITISH_VIRGIN_ISLANDS                      ("VG", "جزایر ویرجین بریتانیا"){ @Override  public int getFlag() { return R.drawable.virginislandsbritish;  } },
   US_VIRGIN_ISLANDS("VI", "جزایر ویرجین ایالات متحده"){ @Override  public int getFlag() { return R.drawable.virginislandsus;  } },
   WALLIS_AND_FUTUNA                           ("WF", "والیس و فوتونا"){ @Override  public int getFlag() { return R.drawable.wallisandfutuna;  } },
   YEMEN                                       ("YE", "یمن"){ @Override  public int getFlag() { return R.drawable.yemen;  } },
    ZAMBIA                                     ("ZM", "زیمباوه"){ @Override  public int getFlag() { return R.drawable.zambia;  } },
    ZIMBABWE                                    ("ZW", "زیمباوه"){ @Override  public int getFlag() { return R.drawable.zimbabwe;  } };

   private String abbreviation;
   private String farsiName;

   Country (String abbreviation, String farsiName){
       this.abbreviation = abbreviation;
       this.farsiName = farsiName;
   }
   public abstract int getFlag();

    public String getAbbreviation() {
        return abbreviation;
    }

    public String getFarsiName() {
        return farsiName;
    }

 @Override
 public String toString() {
  String [] strs = this.name().split("_");
  StringBuilder sb = new StringBuilder();
  for (String str : strs){
   sb.append(str, 0, 1).append(str.substring(1).toLowerCase()).append(" ");
  }
  return sb.toString();
 }

}
      
      
